services:
  test:
    image: annealing-pytorch
    build: .
    command: /bin/bash
    tty: true
    volumes:
      - ./:/opt/work
    working_dir: /opt/work
    # リソースを拡張したい場合の指定（任意）
    shm_size: 4gb
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  mlflow:
    image: annealing-pytorch
    volumes:
      - ./:/opt/work
    working_dir: /opt/work
    ports:
      - 5000:5000
    command: mlflow ui --host 0.0.0.0 
    